### ISSUE TITLE
wagl dig doesn't work on the public IP address, only an internal IP address

### ISSUE THREAD

**Issue by funkytaco** [ahmetalpbalkan/wagl#8]
It looks like I have wagl working with this:

```
WAGL_CONTAINER=`docker run -d --restart=always --name=dns \
    -p 53:53/udp \
    --link "$SWARM_HASH":swarm \
    --volumes-from ssl-data \
    ahmet/wagl wagl \
    --domain my.domain \
    --swarm-cert-path /etc/docker \
    --swarm tcp://swarm:2376`
```

where `ssl-data` is my cert/PEM container.

`docker logs dns` shows:

2015/12/22 20:59:17 Tasks with DNS records: 2
2015/12/22 20:59:17     +RR: A micro-hipchat.my.domain. 1.2.3.4
2015/12/22 20:59:17     +RR: SRV _micro-hipchat._tcp.my.domain. 1.2.3.4:8001
2015/12/22 20:59:17     +RR: A microlith.my.domain. 1.2.3.4
2015/12/22 20:59:17     +RR: SRV _microlith._tcp.my.domain. 1.2.3.4:8000
2015/12/22 20:59:17 Successfully refreshed records.

so it's looks like wagl is working, but for some reason any dig to the DNS shows this:

```
docker exec -it microlith dig micro-hipchat.my.domain
;; reply from unexpected source: 172.17.0.1#53, expected 104.130.0.177#53
;; reply from unexpected source: 172.17.0.1#53, expected 104.130.0.177#53
```

If I dig @172.17.0.1, it works fine, but I don't understand this behavior. wagl is on the IP mentioned.

```
docker port dns 
53/udp -> 104.130.0.177:53
```

**Comment by ahmetb** [comment]
Hmm this seems rather interesting. I remember getting this error while developing wagl but I totally forgot what it was about.

Also, is your dig container configured to use wagl? (I guess you did set `--dns <IP>`  on docker engine, what did you specify as `<IP>` over there?)

**Comment by funkytaco** [comment]
The domain isn't the problem.  I don't want that shared, if you would please remove the domain from your post (sorry about that). I did a CTRL+F replace, but forgot to do it for that part.

And yes, I used `--dns`

```
docker run -p 8000:80 -d -l dns.service=microlith --name microlith --hostname=microlith --dns 104.130.0.177   -t microlith-mvc-nginx:latest`

docker run -p 8001:80 -d -l dns.service=micro-hipchat --name micro-hipchat --hostname=micro-hipchat --link microlith:microlith --dns 104.130.0.177 -t micro-hipchat:latest
```

**Comment by ahmetb** [comment]
Hmm are these machines on the same virtual LAN by any chance? 104.130.0.177 seems like a public IP that I can ping. I don't suggest exposing your internal DNS server to public internet.

So I redacted your domain above, and as you can see below I can do the request just fine:

```
dig @104.130.0.177 A microlith.[redacted]

; <<>> DiG 9.8.3-P1 <<>> @104.130.0.177 A microlith.[redacted]
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 10431
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;microlith.[redacted].      IN  A

;; ANSWER SECTION:
microlith.[redacted].   0   IN  A   104.130.0.177
```

But you're saying this is not working inside container. This is interesting. Can you just do:

```
docker run --rm -i -t --dns 104.130.0.177 ahmet/dev dig A microlith.[redacted].net
```

with my image? Let's see what happens.

**Comment by funkytaco** [comment]
Oh, right, I can use the private IP. I'll teardown the swarm in a bit to do that.

docker run --rm -i -t --dns 104.130.0.177 ahmet/dev dig A microlith.[redacted]

```
;; reply from unexpected source: 172.17.0.1#53, expected 104.130.0.177#53
;; reply from unexpected source: 172.17.0.1#53, expected 104.130.0.177#53
;; reply from unexpected source: 172.17.0.1#53, expected 104.130.0.177#53
; <<>> DiG 9.9.5-9+deb8u3-Debian <<>> A microlith.[redacted]
;; global options: +cmd
;; connection timed out; no servers could be reached
```

But a dig works fine....

```
dig @104.130.0.177 A microlith.[redacted] +short
104.130.0.177
```

**Comment by ahmetb** [comment]
@funkytaco I already redacted all, you're the one not redacting. :)

**Comment by ahmetb** [comment]
Interesting. This command works just fine for me:

```
docker run -i -t --rm --dns 104.130.0.177 ahmet/dev dig A microlith.[redacted].net

; <<>> DiG 9.9.5-9+deb8u3-Debian <<>> A microlith.[redacted].net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1550
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;microlith.[redacted].net       IN  A

;; ANSWER SECTION:
microlith.[redacted].net    0   IN  A   104.130.0.177

;; Query time: 95 msec
;; SERVER: 104.130.0.177#53(104.130.0.177)
;; WHEN: Wed Dec 23 00:23:37 UTC 2015
;; MSG SIZE  rcvd: 76
```

I think there's something wrong with your setup. Try running wagl container with `docker run --net=host` (you'll need to remove `-p 53:53/udp`). This way you'll be directly running on host networking stack. This may solve your problem but I'd say you're not doing your cluster setup right. 

Your hosts ideally should be referring to each other with internal IP addresses rather than public ones.

**Comment by ahmetb** [comment]
Also, it appears like you're trying to plug into TLD domain space (.net), I suggest using wagl only for inter-container communication on a separate domain, such as `swarm.` or `swarm.local.`.

**Comment by funkytaco** [comment]
What does `--net=host` do? I'm still learning Docker every step. I'll try that now.

**Comment by ahmetb** [comment]
You can read https://docs.docker.com/engine/reference/run/

**Comment by funkytaco** [comment]
So it looks like you can't use `--net=host` and `--link "$SWARM_HASH":swarm` ("Conflicting options: --net=host can't be used with links.")

But, once I switched `--dns` to use the private IP and the domain literally to "redacted" ;), it worked. Thank you.

dig micro-hipchat.redacted +short
172.99.65.119

But now I see this won't work for me, as I needed the public IP address, as I need to have my backend server on the monlolithic app get the public IP address for an XHR call to a microservice. Maybe I'll do this via an environment variable somehow. I'll still need this for the backend, though, so that's good.

Thanks for all of your help!

**Comment by ahmetb** [comment]
No worries, glad to help. In order to avoid link, you can change wagl's argument `--swarm SWARM'S_IP:SWARM_PORT` and pass the actual IP addr of swarm and drop `--link` altogether.

Feel free to close the issue if you think your problem is resolved.

**Comment by funkytaco** [comment]
If I setup wagl the way you just suggested then I can't get the IP for the wagl container:

```
docker inspect --format '{{json .NetworkSettings }}' dns | jq
{
  "Bridge": "",
  "SandboxID": "6f75a8b80fbf3b8716533c0a453d94cfa2591ef997922ec3dcb017ac122605a5",
  "HairpinMode": false,
  "LinkLocalIPv6Address": "",
  "LinkLocalIPv6PrefixLen": 0,
  "Ports": {},
  "SandboxKey": "/var/run/docker/netns/default",
  "SecondaryIPAddresses": null,
  "SecondaryIPv6Addresses": null,
  "EndpointID": "",
  "Gateway": "",
  "GlobalIPv6Address": "",
  "GlobalIPv6PrefixLen": 0,
  "IPAddress": "",
  "IPPrefixLen": 0,
  "IPv6Gateway": "",
  "MacAddress": "",
  "Networks": {
    "host": {
      "EndpointID": "2cfda7e1d1b59bba351f0655f958492b410da28ff2ebabe93ba7e1c3d5a821bd",
      "Gateway": "",
      "IPAddress": "",
      "IPPrefixLen": 0,
      "IPv6Gateway": "",
      "GlobalIPv6Address": "",
      "GlobalIPv6PrefixLen": 0,
      "MacAddress": ""
    }
  }
}
```

When wagl started, the logs showed this:

```
docker logs dns
2015/12/23 01:52:53 Configuration:
 - Domain:    "redacted"
 - Listen:    ":53"
 - Swarm:     tcp://172.17.0.3:2376
   - TLS:     /etc/docker (verify: false)
 - External:  true (ns: [69.20.0.164:53,69.20.0.196:53])
 - Refresh:   Every 15s (timeout: 10s) (staleness: 1m0s)
-------------------
2015/12/23 01:52:53 Starting to refresh DNS records every 15s...
2015/12/23 01:52:53 DNS server started listening at :53
```

Since I can't get the IP for wagl container, I had to remove the `--dns` flag since there isn't an IP to add to the resolv.conf (those two "external" DNS are listed in there, though). This was just an excercise to see if this would work better, but in my case it doesn't seem to work at all.

From my app container:
`dig micro-hipchat.redacted +short` returns nothing now.

```
dig micro-hipchat.redacted|grep SERVER
;; SERVER: 69.20.0.164#53(69.20.0.164)
```

Anyways, Happy Holidays! Thanks for all of the help!
